Rolling back c5694, due to test failure:
junit.framework.AssertionFailedError: expected=table actual=tbody 
  at com.google.gwt.user.client.ui.HTMLPanelTest.testCustomRootTag(HTMLPanelTest.java:137) 
  at com.google.gwt.user.client.ui.__HTMLPanelTest_unitTestImpl.doRunTest(transient source for com.google.gwt.user.client.ui.__HTMLPanelTest_unitTestImpl:28)  



git-svn-id: https://google-web-toolkit.googlecode.com/svn/trunk@5695 8db76d5a-ed1c-0410-87a9-c151d255dfc7